#----------------------------------------------------------------------------
#       Make Workspace
#
# 
#
# This file was generated by MPC.  Any changes made directly to
# this file will be lost the next time it is generated.
#
# MPC Command:
# ./mwc.pl -type make ../Test/
#
#----------------------------------------------------------------------------


all: output

depend: output-depend

clean generated realclean check-syntax $(CUSTOM_TARGETS):
	@$(MAKE) -f Makefile.output $(@)

.PHONY: output
output:
	@$(MAKE) -f Makefile.output all

.PHONY: output-depend
output-depend:
	@$(MAKE) -f Makefile.output depend

project_name_list:
	@echo output
